### ISSUE TITLE
Sumokoin Fails to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by DevynCJohnson** [sumoprojects/sumokoin#142]
When using gcc-8 on Ubuntu 18.04, I get the below errors. Ever since the upgrade from Ubuntu 17.10 to Ubuntu 18.04, I get the below error. However, this will build on Ubuntu 17.10.

`[ 47%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_nsec3.c.o

[ 48%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_nsec.c.o

[ 48%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_secalgo.c.o
/home/collier/.sumokoin/sumokoin-master/external/unbound/validator/val_secalgo.c: In function ‘setup_dsa_sig’:

/home/collier/.sumokoin/sumokoin-master/external/unbound/validator/val_secalgo.c:256:8: error: dereferencing pointer to incomplete type ‘DSA_SIG’ {aka ‘struct DSA_SIG_st’}

  dsasig->r = R;

        ^~

/home/collier/.sumokoin/sumokoin-master/external/unbound/validator/val_secalgo.c: In function ‘setup_ecdsa_sig’:

/home/collier/.sumokoin/sumokoin-master/external/unbound/validator/val_secalgo.c:291:11: error: dereferencing pointer to incomplete type ‘ECDSA_SIG’ {aka ‘struct ECDSA_SIG_st’}
  ecdsa_sig->r = BN_bin2bn(*sig, bnsize, ecdsa_sig->r);

           ^~

/home/collier/.sumokoin/sumokoin-master/external/unbound/validator/val_secalgo.c: In function ‘setup_key_digest’:

/home/collier/.sumokoin/sumokoin-master/external/unbound/validator/val_secalgo.c:348:19: warning: implicit declaration of function ‘EVP_dss1’; did you mean ‘EVP_sha1’? [-Wimplicit-function-declaration]

    *digest_type = EVP_dss1();

                   ^~~~~~~~

                   EVP_sha1

/home/collier/.sumokoin/sumokoin-master/external/unbound/validator/val_secalgo.c:348:17: warning: assignment to ‘const EVP_MD *’ {aka ‘const struct evp_md_st *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]

    *digest_type = EVP_dss1();

                 ^

/home/collier/.sumokoin/sumokoin-master/external/unbound/validator/val_secalgo.c: In function ‘verify_canonrrset’:

/home/collier/.sumokoin/sumokoin-master/external/unbound/validator/val_secalgo.c:509:13: error: storage size of ‘ctx’ isn’t known

  EVP_MD_CTX ctx;

             ^~~

/home/collier/.sumokoin/sumokoin-master/external/unbound/validator/val_secalgo.c:560:5: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Wimplicit-function-declaration]

  if(EVP_MD_CTX_cleanup(&ctx) == 0) {

     ^~~~~~~~~~~~~~~~~~

     EVP_MD_CTX_create

external/unbound/CMakeFiles/unbound.dir/build.make:1334: recipe for target 'external/unbound/CMakeFiles/unbound.dir/validator/val_secalgo.c.o' failed

make[2]: *** [external/unbound/CMakeFiles/unbound.dir/validator/val_secalgo.c.o] Error 1

CMakeFiles/Makefile2:201: recipe for target 'external/unbound/CMakeFiles/unbound.dir/all' failed

make[1]: *** [external/unbound/CMakeFiles/unbound.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....

[ 48%] Building CXX object src/ringct/CMakeFiles/obj_ringct.dir/rctTypes.cpp.o

[ 49%] Building C object src/ringct/CMakeFiles/obj_ringct.dir/rctCryptoOps.c.o

[ 49%] Building CXX object src/common/CMakeFiles/obj_common.dir/util.cpp.o

[ 50%] Building CXX object src/common/CMakeFiles/obj_common.dir/i18n.cpp.o

[ 50%] Built target obj_ringct

[ 50%] Building CXX object src/common/CMakeFiles/obj_common.dir/password.cpp.o

[ 51%] Building CXX object src/common/CMakeFiles/obj_common.dir/perf_timer.cpp.o

[ 51%] Building CXX object src/common/CMakeFiles/obj_common.dir/task_region.cpp.o

[ 52%] Building CXX object src/common/CMakeFiles/obj_common.dir/thread_group.cpp.o

[ 52%] Building CXX object src/common/CMakeFiles/obj_common.dir/threadpool.cpp.o

[ 52%] Built target obj_common

Makefile:140: recipe for target 'all' failed

make: *** [all] Error 2`

**Comment by gonultasbu** [comment]
also having similar problems on ubuntu 18.04, most probably linked to OpenSSL

**Comment by gonultasbu** [comment]
Here is the solution 

> sudo apt-get install libssl1.0-dev

credits to: https://github.com/openlink/virtuoso-opensource/issues/663

**Comment by sumogr** [comment]
Resolved
